service: logging

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  role: arn:aws:iam::885121665536:role/myapp-logging-role

functions:
  dispatchErrors:
    handler: handler.dispatchErrors
    events:
      - sns: arn:aws:sns:us-east-1:<account_id>:PRODUCTION_ERRORS